repos:
  - repo: local
    hooks:
      - id: lint
        name: Run Linters
        entry: .\scripts\lint.ps1
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]

      - id: test-imports
        name: Test Import Validation
        entry: .\run.ps1 scripts\validate-imports.py
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]

      - id: run-tests
        name: Run All Tests
        entry: .\run.ps1 tests\run_tests.py all
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
