repos:
  - repo: local
    hooks:
      - id: test-imports
        name: Test Import Validation
        entry: python -c "
import sys
import os
sys.path.insert(0, 'src')
try:
    from testfixture.workflow import *
    from testfixture.issue_processor import *
    print('✅ All imports valid')
except ImportError as e:
    print(f'❌ Import error: {e}')
    sys.exit(1)
"
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]

      - id: run-tests
        name: Run All Tests
        entry: .\run.ps1 tests\run_tests.py all
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
