name: Build

on:
  push:
    branches: [ main ]
    tags-ignore: [ 'v*' ]

env:
  PYTHON_VERSION: '3.11'

jobs:

  build-windows:
    name: Build Windows Executables
    runs-on: windows-latest
    # Skip this job if the commit is a release commit (handled by build-and-release.yml)
    if: "${{ !contains(github.event.head_commit.message, 'chore: release version') }}"
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Create virtual environment
      run: |
        python -m venv .venv
        
    - name: Install dependencies
      run: |
        .venv\Scripts\Activate.ps1
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Generate PyInstaller spec file
      run: |
        .venv\Scripts\Activate.ps1
        echo "Generating PyInstaller spec file..."
        python tools\generate-spec.py
        
    - name: Build Windows executables
      run: |
        .venv\Scripts\Activate.ps1
        echo "Building on Windows..."
        powershell -ExecutionPolicy Bypass -File scripts/build.ps1 -Platform windows
        
    - name: Upload Windows Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-executables
        path: build-executables/
        retention-days: 30
